create table
  public.states (
    id bigint generated by default as identity not null,
    name character varying null default '200'::character varying,
    uf character varying null default '3'::character varying,
    created_at timestamp with time zone null default now(),
    constraint states_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.cities (
    id bigint generated by default as identity not null,
    name character varying null default '200'::character varying,
    state_id bigint null,
    created_at timestamp with time zone null default now(),
    constraint cities_pkey primary key (id),
    constraint cities_state_id_fkey foreign key (state_id) references states (id)
  ) tablespace pg_default;

create table
  public.sectors (
    id uuid not null default gen_random_uuid (),
    name character varying null,
    slug character varying null,
    description text null,
    how_to_get_there text null,
    state_id bigint null,
    city_id bigint null,
    stars bigint null default '0'::bigint,
    state_name text null,
    city_name text null,
    created_at timestamp with time zone null default now(),
    updated_at timestamp with time zone null default now(),
    constraint sectors_pkey primary key (id),
    constraint sectors_state_id_fkey foreign key (state_id) references states (id),
    constraint sectors_city_id_fkey foreign key (city_id) references cities (id)
  ) tablespace pg_default;

create table
  public.profiles (
    id uuid not null default gen_random_uuid (),
    name character varying null,
    photo text null,
    city_id bigint null,
    state_id bigint null,
    is_conqueror character varying null,
    is_partner character varying null,
    state_name text null,
    city_name text null,
    created_at timestamp with time zone null default now(),
    updated_at timestamp with time zone null default now(),
    constraint profiles_pkey primary key (id),
    constraint profiles_city_id_fkey foreign key (city_id) references cities (id),
    constraint profiles_state_id_fkey foreign key (state_id) references states (id)
  ) tablespace pg_default;

create table
  public.conquerors (
    id uuid not null default gen_random_uuid (),
    name character varying null default '255'::character varying,
    created_at timestamp with time zone null default now(),
    updated_at timestamp with time zone null default now(),
    constraint conquerors_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.climb_routes (
    id uuid not null default gen_random_uuid (),
    name text null,
    slug text null,
    sector_id uuid null,
    modality text null,
    length text null,
    wall_face text null,
    type_of_climbing text null,
    equipment json null,
    grade json null,
    created_at timestamp with time zone null default now(),
    updated_at timestamp with time zone null default now(),
    description text null,
    constraint climb_routes_pkey primary key (id),
    constraint climb_routes_sector_id_fkey foreign key (sector_id) references sectors (id)
  ) tablespace pg_default;

create table
  public.routes_conquerors (
    id uuid not null default gen_random_uuid (),
    climb_route_id uuid not null,
    conqueror_id uuid not null,
    constraint routes_conquerors_pkey primary key (id, climb_route_id, conqueror_id),
    constraint routes_conquerors_climb_route_id_fkey foreign key (climb_route_id) references climb_routes (id) on delete cascade,
    constraint routes_conquerors_conqueror_id_fkey foreign key (conqueror_id) references conquerors (id)
  ) tablespace pg_default;
