# Main Workflow

name: Deploy to production
on:
  push:
    branches: [main]

env:
  PROJECT_ID: ${{ secrets.PROD_SUPABASE_PROJECT_ID }}
  SUPABASE_DB_PASSWORD: ${{ secrets.PROD_SUPABASE_DB_PASSWORD }}
  SUPABASE_ACCESS_TOKEN: ${{ secrets.PROD_SUPABASE_ACCESS_TOKEN }}

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out codebase
        uses: actions/checkout@v2

      - name: Making migrations in Dev environment
        uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: supabase link --project-ref $PROJECT_ID -p $SUPABASE_DB_PASSWORD
      - run: supabase db push
